language: cpp
compiler:
 - gcc
env:
 - ZMQ="https://github.com/zeromq/zeromq3-x.git"
 - ZMQ="https://github.com/zeromq/zeromq4-x.git" SODIUM="git://github.com/jedisct1/libsodium.git -b 0.4.5"
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq qtdeclarative5-dev
 - sudo apt-get install uuid-dev
 - '[ -z "$SODIUM" ] || git clone --depth 1 $SODIUM ~/libsodium'
 - '[ -z "$SODIUM" ] || pushd ~/libsodium'
 - '[ -z "$SODIUM" ] || ./autogen.sh'
 - '[ -z "$SODIUM" ] || ./configure'
 - '[ -z "$SODIUM" ] || make'
 - '[ -z "$SODIUM" ] || sudo make install'
 - '[ -z "$SODIUM" ] || popd'
 - git clone --depth 1 $ZMQ ~/zmqlib
 - pushd ~/zmqlib
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
 - sudo /sbin/ldconfig
 - popd

script:
 - qmake -qt=qt5
 - make
 - make check
