language: cpp
compiler:
 - gcc
env:
 - ZMQ="git://github.com/zeromq/zeromq3-x.git -b v3.2.4"
 - ZMQ="git://github.com/zeromq/zeromq4-x.git -b v4.0.3" SODIUM="git://github.com/jedisct1/libsodium.git -b 0.4.5"
before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt541
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt54base qt54declarative
 - sudo apt-get install uuid-dev
 - '[ -z "$SODIUM" ] || git clone --depth 1 $SODIUM ~/libsodium'
 - '[ -z "$SODIUM" ] || pushd ~/libsodium'
 - '[ -z "$SODIUM" ] || ./autogen.sh'
 - '[ -z "$SODIUM" ] || ./configure'
 - '[ -z "$SODIUM" ] || make'
 - '[ -z "$SODIUM" ] || sudo make install'
 - '[ -z "$SODIUM" ] || popd'
 - git clone --depth 1 $ZMQ ~/zmqlib
 - pushd ~/zmqlib
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
 - sudo /sbin/ldconfig
 - popd

script:
 - source /opt/qt54/bin/qt54-env.sh
 - qmake
 - make
